import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthContext from './auth-context'
import Sidebar from '@/components/sidebar/sidebar'
import Profile from '@/components/profile/profile'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <AuthContext>
          <header className="flex justify-end">
            <Profile />
          </header>
          <Sidebar />
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
