import { Inter } from 'next/font/google'

import type { Metadata } from 'next'
import './globals.css'
import AuthContext from '@/containers/auth-context'
import { TodayContextProvider } from '@/hooks/useToday'

import Sidebar from '@/components/sidebar/sidebar'
import Profile from '@/components/profile/profile'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <AuthContext>
          <TodayContextProvider>
            <div className="min-h-screen bg-neutral-100">
              <header className="flex justify-end h-[60px] items-center px-5">
                <Profile />
              </header>
              <div className="flex min-h-[calc(100vh-60px)] gap-1">
                <Sidebar />
                <div className="flex-1">{children}</div>
              </div>
            </div>
          </TodayContextProvider>
        </AuthContext>
      </body>
    </html>
  )
}
